### ISSUE TITLE
incompatible node version

### ISSUE THREAD

**Issue by luizkowalski** [stimulus-components/stimulus-clipboard#12]
hey 👋🏻 
thanks a lot for this lib!

I'm trying to upgrade to either 3.4 or 4.0 and I keep getting the same error:

```
error stimulus-clipboard@4.0.0: The engine "node" is incompatible with this module. Expected version "18". Got "20.2.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

checking the diff, I noticed you introduce a hardcoded node version in the requirements [here](https://github.com/stimulus-components/stimulus-clipboard/compare/v3.3.0...v4.0.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R4). I'm not a JS developer but I wonder if it is possible to have a more relaxed node version pinning like `>= 18` or something

**Comment by semanticart** [comment]
I'd also love to see this version relaxed.

**Comment by guillaumebriday** [comment]
Oups my bad, 

Will deploy a fix later today, sorry about that

**Comment by guillaumebriday** [comment]
There you go 👉 https://github.com/stimulus-components/stimulus-clipboard/releases/tag/v4.0.1

**Comment by guillaumebriday** [comment]
Please let me know if it fixed your problem 👍

**Comment by luizkowalski** [comment]
all good now, thanks a lot!
