### ISSUE TITLE
Allow content to be copied in values

### ISSUE THREAD

**Issue by tacman** [stimulus-components/stimulus-clipboard#5]
Instead of requiring an HTMLInputElement, which has the display problem, what about allowing the content to be copied in the controller values?

Instead of
```html
<div data-controller="clipboard" data-clipboard-success-content="Copied!">
  <input type="text" value="Click the button to copy me!" data-clipboard-target="source" />
```

```html
<div data-controller="clipboard" 
data-clipboard-content="Click the button to copy me (this isn't visible, but it could be some long and garly url or uuid!)"
data-clipboard-success-content="Copied!">
```

I'm not sure if this is even possible, I'm not sure how 'select' and   document.execCommand('copy') work.

**Comment by guillaumebriday** [comment]
@tacman With the new 3.2.0 release you should be able to do that with a hidden field 👍
